# Generated by Django 4.1.7 on 2023-03-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="data_publicacao",
            field=models.DateField(verbose_name="Data de Publicação"),
        ),
    ]
